; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@^2.1.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	DHT20@0.3.1
	thingsboard/ThingsBoard@^0.15.0
	markruys/DHT@^1.0.0
	vshymanskyy/TinyGSM@^0.12.0
lib_ldf_mode = deep
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.mcu = esp32

[env:yolo_uno]
platform = espressif32
board = yolo_uno
framework = arduino
build_unflags = -Os
build_flags = 
	-O1
	-include project_config.h
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	mathieucarbou/ESPAsyncWebServer@^3.6.0
	DHT20@0.3.1
	SPIFFS@2.0.0
	WiFi@2.0.0
	thingsboard/ThingsBoard@^0.15.0
	markruys/DHT@^1.0.0
	vshymanskyy/TinyGSM@^0.12.0
lib_extra_dirs = 
	lib
	lib/Utils
lib_ldf_mode = deep
board_build.filesystem = spiffs
board_build.partitions = yolo_uno_8MB.csv
monitor_speed = 115200
